### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kiwih** [AzemOcram/OcramTower#3]
Under what license is this developed as? I am interested in developing this concept further, but would like to know how it is licensed.

**Comment by AzemOcram** [comment]
I apologize for not responding earlier. I have been super busy with life since around Christmas (which is why I have not updated since last year). OcramTower is Creative Commons Attribution. OpenTower was open source of some sort, possibly Creative Commons Attribution. If you want to develop a tower simulator and have at least the Beta before mid 2016, I encourage you to go ahead and I will try to help as much as possible. SomaSim just started working on their own game called Project Highrise and their release date is roughly mid 2016. I was planning on starting back up on my work for OcramTower after seeing what Project Highrise does right and what it doesn't do that I had planned on implementing since 2009.

**Comment by kiwih** [comment]
That sounds good. You should probably commit that license to the source!
